apiVersion: v1
kind: ConfigMap
metadata:
  name: quakewatch
  namespace: final-project
data:
  QUAKEWATCH__LOG_PATH: /tmp/logs
  MPLBACKEND: Agg
  MPLCONFIGDIR: /tmp/matplotlib
  DUCKDB__PATH: /data/earthquakes.duckdb
  QUACK__HOST: duckdb
  QUACK__PORT: "9494"