# 1. WORKFLOW IDENTITY
name: push into the branches, except main branch
run-name: runs pylint on python files and builds the Docker image

# 2. TRIGGER EVENTS
on:
  push:
    branches-ignore:
      - 'main'
    
# 4. JOBS AND STEPS
jobs:
  checkout-and-message:
    runs-on: ubuntu-latest
    steps:
      - name: pylint
        # old version, get "Warning: Node.js 20 actions are deprecated."
        uses: actions/checkout@v6

      - name: build the Docker image
        run: echo "here will pylint check"